#ifndef MINEOLA_PREFIX_H
#define MINEOLA_PREFIX_H

#define GLM_ENABLE_EXPERIMENTAL
#define GLM_FORCE_CTOR_INIT

#ifdef __ANDROID_API__
#define BOOST_UUID_RANDOM_PROVIDER_FORCE_POSIX
#endif

#define MINEOLA_USE_STBIMAGE

#endif /* MINEOLA_PREFIX_H */
